// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqvqvsbpszgbottgtcrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdnF2c2Jwc3pnYm90dGd0Y3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjczMjUsImV4cCI6MjA3MzIwMzMyNX0.hr4XCGOBvZGjSNKIMWHOCYJ0BFfnCD1H-fLY3MPlgyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});